# Generated by Django 5.2.6 on 2025-10-26 20:59

import cloudinary_storage.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=core.models.profile_image_upload_path),
        ),
    ]
