# Generated by Django 5.2.6 on 2025-10-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_valoracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
