# Generated by Django 5.2.6 on 2025-10-27 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
